// Code generated by go-swagger; DO NOT EDIT.

package peer_swap

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPeerSwapListPeersParams creates a new PeerSwapListPeersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPeerSwapListPeersParams() *PeerSwapListPeersParams {
	return &PeerSwapListPeersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPeerSwapListPeersParamsWithTimeout creates a new PeerSwapListPeersParams object
// with the ability to set a timeout on a request.
func NewPeerSwapListPeersParamsWithTimeout(timeout time.Duration) *PeerSwapListPeersParams {
	return &PeerSwapListPeersParams{
		timeout: timeout,
	}
}

// NewPeerSwapListPeersParamsWithContext creates a new PeerSwapListPeersParams object
// with the ability to set a context for a request.
func NewPeerSwapListPeersParamsWithContext(ctx context.Context) *PeerSwapListPeersParams {
	return &PeerSwapListPeersParams{
		Context: ctx,
	}
}

// NewPeerSwapListPeersParamsWithHTTPClient creates a new PeerSwapListPeersParams object
// with the ability to set a custom HTTPClient for a request.
func NewPeerSwapListPeersParamsWithHTTPClient(client *http.Client) *PeerSwapListPeersParams {
	return &PeerSwapListPeersParams{
		HTTPClient: client,
	}
}

/*
PeerSwapListPeersParams contains all the parameters to send to the API endpoint

	for the peer swap list peers operation.

	Typically these are written to a http.Request.
*/
type PeerSwapListPeersParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the peer swap list peers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PeerSwapListPeersParams) WithDefaults() *PeerSwapListPeersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the peer swap list peers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PeerSwapListPeersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the peer swap list peers params
func (o *PeerSwapListPeersParams) WithTimeout(timeout time.Duration) *PeerSwapListPeersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the peer swap list peers params
func (o *PeerSwapListPeersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the peer swap list peers params
func (o *PeerSwapListPeersParams) WithContext(ctx context.Context) *PeerSwapListPeersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the peer swap list peers params
func (o *PeerSwapListPeersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the peer swap list peers params
func (o *PeerSwapListPeersParams) WithHTTPClient(client *http.Client) *PeerSwapListPeersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the peer swap list peers params
func (o *PeerSwapListPeersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PeerSwapListPeersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
