// Code generated by go-swagger; DO NOT EDIT.

package peer_swap

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"peerswap-web/models"
)

// PeerSwapListActiveSwapsReader is a Reader for the PeerSwapListActiveSwaps structure.
type PeerSwapListActiveSwapsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PeerSwapListActiveSwapsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPeerSwapListActiveSwapsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPeerSwapListActiveSwapsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPeerSwapListActiveSwapsOK creates a PeerSwapListActiveSwapsOK with default headers values
func NewPeerSwapListActiveSwapsOK() *PeerSwapListActiveSwapsOK {
	return &PeerSwapListActiveSwapsOK{}
}

/*
PeerSwapListActiveSwapsOK describes a response with status code 200, with default header values.

A successful response.
*/
type PeerSwapListActiveSwapsOK struct {
	Payload *models.PeerswapListSwapsResponse
}

// IsSuccess returns true when this peer swap list active swaps o k response has a 2xx status code
func (o *PeerSwapListActiveSwapsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this peer swap list active swaps o k response has a 3xx status code
func (o *PeerSwapListActiveSwapsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this peer swap list active swaps o k response has a 4xx status code
func (o *PeerSwapListActiveSwapsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this peer swap list active swaps o k response has a 5xx status code
func (o *PeerSwapListActiveSwapsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this peer swap list active swaps o k response a status code equal to that given
func (o *PeerSwapListActiveSwapsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the peer swap list active swaps o k response
func (o *PeerSwapListActiveSwapsOK) Code() int {
	return 200
}

func (o *PeerSwapListActiveSwapsOK) Error() string {
	return fmt.Sprintf("[GET /v1/swaps/active][%d] peerSwapListActiveSwapsOK  %+v", 200, o.Payload)
}

func (o *PeerSwapListActiveSwapsOK) String() string {
	return fmt.Sprintf("[GET /v1/swaps/active][%d] peerSwapListActiveSwapsOK  %+v", 200, o.Payload)
}

func (o *PeerSwapListActiveSwapsOK) GetPayload() *models.PeerswapListSwapsResponse {
	return o.Payload
}

func (o *PeerSwapListActiveSwapsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PeerswapListSwapsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPeerSwapListActiveSwapsDefault creates a PeerSwapListActiveSwapsDefault with default headers values
func NewPeerSwapListActiveSwapsDefault(code int) *PeerSwapListActiveSwapsDefault {
	return &PeerSwapListActiveSwapsDefault{
		_statusCode: code,
	}
}

/*
PeerSwapListActiveSwapsDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type PeerSwapListActiveSwapsDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this peer swap list active swaps default response has a 2xx status code
func (o *PeerSwapListActiveSwapsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this peer swap list active swaps default response has a 3xx status code
func (o *PeerSwapListActiveSwapsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this peer swap list active swaps default response has a 4xx status code
func (o *PeerSwapListActiveSwapsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this peer swap list active swaps default response has a 5xx status code
func (o *PeerSwapListActiveSwapsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this peer swap list active swaps default response a status code equal to that given
func (o *PeerSwapListActiveSwapsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the peer swap list active swaps default response
func (o *PeerSwapListActiveSwapsDefault) Code() int {
	return o._statusCode
}

func (o *PeerSwapListActiveSwapsDefault) Error() string {
	return fmt.Sprintf("[GET /v1/swaps/active][%d] PeerSwap_ListActiveSwaps default  %+v", o._statusCode, o.Payload)
}

func (o *PeerSwapListActiveSwapsDefault) String() string {
	return fmt.Sprintf("[GET /v1/swaps/active][%d] PeerSwap_ListActiveSwaps default  %+v", o._statusCode, o.Payload)
}

func (o *PeerSwapListActiveSwapsDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *PeerSwapListActiveSwapsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
