// Code generated by go-swagger; DO NOT EDIT.

package peer_swap

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"peerswap-web/models"
)

// NewPeerSwapAllowSwapRequestsParams creates a new PeerSwapAllowSwapRequestsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPeerSwapAllowSwapRequestsParams() *PeerSwapAllowSwapRequestsParams {
	return &PeerSwapAllowSwapRequestsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPeerSwapAllowSwapRequestsParamsWithTimeout creates a new PeerSwapAllowSwapRequestsParams object
// with the ability to set a timeout on a request.
func NewPeerSwapAllowSwapRequestsParamsWithTimeout(timeout time.Duration) *PeerSwapAllowSwapRequestsParams {
	return &PeerSwapAllowSwapRequestsParams{
		timeout: timeout,
	}
}

// NewPeerSwapAllowSwapRequestsParamsWithContext creates a new PeerSwapAllowSwapRequestsParams object
// with the ability to set a context for a request.
func NewPeerSwapAllowSwapRequestsParamsWithContext(ctx context.Context) *PeerSwapAllowSwapRequestsParams {
	return &PeerSwapAllowSwapRequestsParams{
		Context: ctx,
	}
}

// NewPeerSwapAllowSwapRequestsParamsWithHTTPClient creates a new PeerSwapAllowSwapRequestsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPeerSwapAllowSwapRequestsParamsWithHTTPClient(client *http.Client) *PeerSwapAllowSwapRequestsParams {
	return &PeerSwapAllowSwapRequestsParams{
		HTTPClient: client,
	}
}

/*
PeerSwapAllowSwapRequestsParams contains all the parameters to send to the API endpoint

	for the peer swap allow swap requests operation.

	Typically these are written to a http.Request.
*/
type PeerSwapAllowSwapRequestsParams struct {

	// Body.
	Body *models.PeerswapAllowSwapRequestsRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the peer swap allow swap requests params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PeerSwapAllowSwapRequestsParams) WithDefaults() *PeerSwapAllowSwapRequestsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the peer swap allow swap requests params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PeerSwapAllowSwapRequestsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the peer swap allow swap requests params
func (o *PeerSwapAllowSwapRequestsParams) WithTimeout(timeout time.Duration) *PeerSwapAllowSwapRequestsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the peer swap allow swap requests params
func (o *PeerSwapAllowSwapRequestsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the peer swap allow swap requests params
func (o *PeerSwapAllowSwapRequestsParams) WithContext(ctx context.Context) *PeerSwapAllowSwapRequestsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the peer swap allow swap requests params
func (o *PeerSwapAllowSwapRequestsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the peer swap allow swap requests params
func (o *PeerSwapAllowSwapRequestsParams) WithHTTPClient(client *http.Client) *PeerSwapAllowSwapRequestsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the peer swap allow swap requests params
func (o *PeerSwapAllowSwapRequestsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the peer swap allow swap requests params
func (o *PeerSwapAllowSwapRequestsParams) WithBody(body *models.PeerswapAllowSwapRequestsRequest) *PeerSwapAllowSwapRequestsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the peer swap allow swap requests params
func (o *PeerSwapAllowSwapRequestsParams) SetBody(body *models.PeerswapAllowSwapRequestsRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PeerSwapAllowSwapRequestsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
