// Code generated by go-swagger; DO NOT EDIT.

package peer_swap

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"peerswap-web/models"
)

// PeerSwapSwapOutReader is a Reader for the PeerSwapSwapOut structure.
type PeerSwapSwapOutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PeerSwapSwapOutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPeerSwapSwapOutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPeerSwapSwapOutDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPeerSwapSwapOutOK creates a PeerSwapSwapOutOK with default headers values
func NewPeerSwapSwapOutOK() *PeerSwapSwapOutOK {
	return &PeerSwapSwapOutOK{}
}

/*
PeerSwapSwapOutOK describes a response with status code 200, with default header values.

A successful response.
*/
type PeerSwapSwapOutOK struct {
	Payload *models.PeerswapSwapResponse
}

// IsSuccess returns true when this peer swap swap out o k response has a 2xx status code
func (o *PeerSwapSwapOutOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this peer swap swap out o k response has a 3xx status code
func (o *PeerSwapSwapOutOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this peer swap swap out o k response has a 4xx status code
func (o *PeerSwapSwapOutOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this peer swap swap out o k response has a 5xx status code
func (o *PeerSwapSwapOutOK) IsServerError() bool {
	return false
}

// IsCode returns true when this peer swap swap out o k response a status code equal to that given
func (o *PeerSwapSwapOutOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the peer swap swap out o k response
func (o *PeerSwapSwapOutOK) Code() int {
	return 200
}

func (o *PeerSwapSwapOutOK) Error() string {
	return fmt.Sprintf("[POST /v1/swaps/swapout][%d] peerSwapSwapOutOK  %+v", 200, o.Payload)
}

func (o *PeerSwapSwapOutOK) String() string {
	return fmt.Sprintf("[POST /v1/swaps/swapout][%d] peerSwapSwapOutOK  %+v", 200, o.Payload)
}

func (o *PeerSwapSwapOutOK) GetPayload() *models.PeerswapSwapResponse {
	return o.Payload
}

func (o *PeerSwapSwapOutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PeerswapSwapResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPeerSwapSwapOutDefault creates a PeerSwapSwapOutDefault with default headers values
func NewPeerSwapSwapOutDefault(code int) *PeerSwapSwapOutDefault {
	return &PeerSwapSwapOutDefault{
		_statusCode: code,
	}
}

/*
PeerSwapSwapOutDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type PeerSwapSwapOutDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this peer swap swap out default response has a 2xx status code
func (o *PeerSwapSwapOutDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this peer swap swap out default response has a 3xx status code
func (o *PeerSwapSwapOutDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this peer swap swap out default response has a 4xx status code
func (o *PeerSwapSwapOutDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this peer swap swap out default response has a 5xx status code
func (o *PeerSwapSwapOutDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this peer swap swap out default response a status code equal to that given
func (o *PeerSwapSwapOutDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the peer swap swap out default response
func (o *PeerSwapSwapOutDefault) Code() int {
	return o._statusCode
}

func (o *PeerSwapSwapOutDefault) Error() string {
	return fmt.Sprintf("[POST /v1/swaps/swapout][%d] PeerSwap_SwapOut default  %+v", o._statusCode, o.Payload)
}

func (o *PeerSwapSwapOutDefault) String() string {
	return fmt.Sprintf("[POST /v1/swaps/swapout][%d] PeerSwap_SwapOut default  %+v", o._statusCode, o.Payload)
}

func (o *PeerSwapSwapOutDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *PeerSwapSwapOutDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
