// Code generated by go-swagger; DO NOT EDIT.

package peer_swap

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"peerswap-web/models"
)

// NewPeerSwapStopParams creates a new PeerSwapStopParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPeerSwapStopParams() *PeerSwapStopParams {
	return &PeerSwapStopParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPeerSwapStopParamsWithTimeout creates a new PeerSwapStopParams object
// with the ability to set a timeout on a request.
func NewPeerSwapStopParamsWithTimeout(timeout time.Duration) *PeerSwapStopParams {
	return &PeerSwapStopParams{
		timeout: timeout,
	}
}

// NewPeerSwapStopParamsWithContext creates a new PeerSwapStopParams object
// with the ability to set a context for a request.
func NewPeerSwapStopParamsWithContext(ctx context.Context) *PeerSwapStopParams {
	return &PeerSwapStopParams{
		Context: ctx,
	}
}

// NewPeerSwapStopParamsWithHTTPClient creates a new PeerSwapStopParams object
// with the ability to set a custom HTTPClient for a request.
func NewPeerSwapStopParamsWithHTTPClient(client *http.Client) *PeerSwapStopParams {
	return &PeerSwapStopParams{
		HTTPClient: client,
	}
}

/*
PeerSwapStopParams contains all the parameters to send to the API endpoint

	for the peer swap stop operation.

	Typically these are written to a http.Request.
*/
type PeerSwapStopParams struct {

	// Body.
	Body models.PeerswapEmpty

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the peer swap stop params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PeerSwapStopParams) WithDefaults() *PeerSwapStopParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the peer swap stop params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PeerSwapStopParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the peer swap stop params
func (o *PeerSwapStopParams) WithTimeout(timeout time.Duration) *PeerSwapStopParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the peer swap stop params
func (o *PeerSwapStopParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the peer swap stop params
func (o *PeerSwapStopParams) WithContext(ctx context.Context) *PeerSwapStopParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the peer swap stop params
func (o *PeerSwapStopParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the peer swap stop params
func (o *PeerSwapStopParams) WithHTTPClient(client *http.Client) *PeerSwapStopParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the peer swap stop params
func (o *PeerSwapStopParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the peer swap stop params
func (o *PeerSwapStopParams) WithBody(body models.PeerswapEmpty) *PeerSwapStopParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the peer swap stop params
func (o *PeerSwapStopParams) SetBody(body models.PeerswapEmpty) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PeerSwapStopParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
