// Code generated by go-swagger; DO NOT EDIT.

package peer_swap

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"peerswap-web/models"
)

// NewPeerSwapAddPeerParams creates a new PeerSwapAddPeerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPeerSwapAddPeerParams() *PeerSwapAddPeerParams {
	return &PeerSwapAddPeerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPeerSwapAddPeerParamsWithTimeout creates a new PeerSwapAddPeerParams object
// with the ability to set a timeout on a request.
func NewPeerSwapAddPeerParamsWithTimeout(timeout time.Duration) *PeerSwapAddPeerParams {
	return &PeerSwapAddPeerParams{
		timeout: timeout,
	}
}

// NewPeerSwapAddPeerParamsWithContext creates a new PeerSwapAddPeerParams object
// with the ability to set a context for a request.
func NewPeerSwapAddPeerParamsWithContext(ctx context.Context) *PeerSwapAddPeerParams {
	return &PeerSwapAddPeerParams{
		Context: ctx,
	}
}

// NewPeerSwapAddPeerParamsWithHTTPClient creates a new PeerSwapAddPeerParams object
// with the ability to set a custom HTTPClient for a request.
func NewPeerSwapAddPeerParamsWithHTTPClient(client *http.Client) *PeerSwapAddPeerParams {
	return &PeerSwapAddPeerParams{
		HTTPClient: client,
	}
}

/*
PeerSwapAddPeerParams contains all the parameters to send to the API endpoint

	for the peer swap add peer operation.

	Typically these are written to a http.Request.
*/
type PeerSwapAddPeerParams struct {

	// Body.
	Body *models.PeerswapAddPeerRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the peer swap add peer params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PeerSwapAddPeerParams) WithDefaults() *PeerSwapAddPeerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the peer swap add peer params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PeerSwapAddPeerParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the peer swap add peer params
func (o *PeerSwapAddPeerParams) WithTimeout(timeout time.Duration) *PeerSwapAddPeerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the peer swap add peer params
func (o *PeerSwapAddPeerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the peer swap add peer params
func (o *PeerSwapAddPeerParams) WithContext(ctx context.Context) *PeerSwapAddPeerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the peer swap add peer params
func (o *PeerSwapAddPeerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the peer swap add peer params
func (o *PeerSwapAddPeerParams) WithHTTPClient(client *http.Client) *PeerSwapAddPeerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the peer swap add peer params
func (o *PeerSwapAddPeerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the peer swap add peer params
func (o *PeerSwapAddPeerParams) WithBody(body *models.PeerswapAddPeerRequest) *PeerSwapAddPeerParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the peer swap add peer params
func (o *PeerSwapAddPeerParams) SetBody(body *models.PeerswapAddPeerRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PeerSwapAddPeerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
