// Code generated by go-swagger; DO NOT EDIT.

package peer_swap

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"peerswap-web/models"
)

// NewPeerSwapRemovePeerParams creates a new PeerSwapRemovePeerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPeerSwapRemovePeerParams() *PeerSwapRemovePeerParams {
	return &PeerSwapRemovePeerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPeerSwapRemovePeerParamsWithTimeout creates a new PeerSwapRemovePeerParams object
// with the ability to set a timeout on a request.
func NewPeerSwapRemovePeerParamsWithTimeout(timeout time.Duration) *PeerSwapRemovePeerParams {
	return &PeerSwapRemovePeerParams{
		timeout: timeout,
	}
}

// NewPeerSwapRemovePeerParamsWithContext creates a new PeerSwapRemovePeerParams object
// with the ability to set a context for a request.
func NewPeerSwapRemovePeerParamsWithContext(ctx context.Context) *PeerSwapRemovePeerParams {
	return &PeerSwapRemovePeerParams{
		Context: ctx,
	}
}

// NewPeerSwapRemovePeerParamsWithHTTPClient creates a new PeerSwapRemovePeerParams object
// with the ability to set a custom HTTPClient for a request.
func NewPeerSwapRemovePeerParamsWithHTTPClient(client *http.Client) *PeerSwapRemovePeerParams {
	return &PeerSwapRemovePeerParams{
		HTTPClient: client,
	}
}

/*
PeerSwapRemovePeerParams contains all the parameters to send to the API endpoint

	for the peer swap remove peer operation.

	Typically these are written to a http.Request.
*/
type PeerSwapRemovePeerParams struct {

	// Body.
	Body *models.PeerswapRemovePeerRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the peer swap remove peer params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PeerSwapRemovePeerParams) WithDefaults() *PeerSwapRemovePeerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the peer swap remove peer params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PeerSwapRemovePeerParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the peer swap remove peer params
func (o *PeerSwapRemovePeerParams) WithTimeout(timeout time.Duration) *PeerSwapRemovePeerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the peer swap remove peer params
func (o *PeerSwapRemovePeerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the peer swap remove peer params
func (o *PeerSwapRemovePeerParams) WithContext(ctx context.Context) *PeerSwapRemovePeerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the peer swap remove peer params
func (o *PeerSwapRemovePeerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the peer swap remove peer params
func (o *PeerSwapRemovePeerParams) WithHTTPClient(client *http.Client) *PeerSwapRemovePeerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the peer swap remove peer params
func (o *PeerSwapRemovePeerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the peer swap remove peer params
func (o *PeerSwapRemovePeerParams) WithBody(body *models.PeerswapRemovePeerRequest) *PeerSwapRemovePeerParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the peer swap remove peer params
func (o *PeerSwapRemovePeerParams) SetBody(body *models.PeerswapRemovePeerRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PeerSwapRemovePeerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
