// Code generated by go-swagger; DO NOT EDIT.

package peer_swap

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"peerswap-web/models"
)

// PeerSwapLiquidSendToAddressReader is a Reader for the PeerSwapLiquidSendToAddress structure.
type PeerSwapLiquidSendToAddressReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PeerSwapLiquidSendToAddressReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPeerSwapLiquidSendToAddressOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPeerSwapLiquidSendToAddressDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPeerSwapLiquidSendToAddressOK creates a PeerSwapLiquidSendToAddressOK with default headers values
func NewPeerSwapLiquidSendToAddressOK() *PeerSwapLiquidSendToAddressOK {
	return &PeerSwapLiquidSendToAddressOK{}
}

/*
PeerSwapLiquidSendToAddressOK describes a response with status code 200, with default header values.

A successful response.
*/
type PeerSwapLiquidSendToAddressOK struct {
	Payload *models.PeerswapSendToAddressResponse
}

// IsSuccess returns true when this peer swap liquid send to address o k response has a 2xx status code
func (o *PeerSwapLiquidSendToAddressOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this peer swap liquid send to address o k response has a 3xx status code
func (o *PeerSwapLiquidSendToAddressOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this peer swap liquid send to address o k response has a 4xx status code
func (o *PeerSwapLiquidSendToAddressOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this peer swap liquid send to address o k response has a 5xx status code
func (o *PeerSwapLiquidSendToAddressOK) IsServerError() bool {
	return false
}

// IsCode returns true when this peer swap liquid send to address o k response a status code equal to that given
func (o *PeerSwapLiquidSendToAddressOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the peer swap liquid send to address o k response
func (o *PeerSwapLiquidSendToAddressOK) Code() int {
	return 200
}

func (o *PeerSwapLiquidSendToAddressOK) Error() string {
	return fmt.Sprintf("[POST /v1/liquid/send][%d] peerSwapLiquidSendToAddressOK  %+v", 200, o.Payload)
}

func (o *PeerSwapLiquidSendToAddressOK) String() string {
	return fmt.Sprintf("[POST /v1/liquid/send][%d] peerSwapLiquidSendToAddressOK  %+v", 200, o.Payload)
}

func (o *PeerSwapLiquidSendToAddressOK) GetPayload() *models.PeerswapSendToAddressResponse {
	return o.Payload
}

func (o *PeerSwapLiquidSendToAddressOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PeerswapSendToAddressResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPeerSwapLiquidSendToAddressDefault creates a PeerSwapLiquidSendToAddressDefault with default headers values
func NewPeerSwapLiquidSendToAddressDefault(code int) *PeerSwapLiquidSendToAddressDefault {
	return &PeerSwapLiquidSendToAddressDefault{
		_statusCode: code,
	}
}

/*
PeerSwapLiquidSendToAddressDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type PeerSwapLiquidSendToAddressDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this peer swap liquid send to address default response has a 2xx status code
func (o *PeerSwapLiquidSendToAddressDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this peer swap liquid send to address default response has a 3xx status code
func (o *PeerSwapLiquidSendToAddressDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this peer swap liquid send to address default response has a 4xx status code
func (o *PeerSwapLiquidSendToAddressDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this peer swap liquid send to address default response has a 5xx status code
func (o *PeerSwapLiquidSendToAddressDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this peer swap liquid send to address default response a status code equal to that given
func (o *PeerSwapLiquidSendToAddressDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the peer swap liquid send to address default response
func (o *PeerSwapLiquidSendToAddressDefault) Code() int {
	return o._statusCode
}

func (o *PeerSwapLiquidSendToAddressDefault) Error() string {
	return fmt.Sprintf("[POST /v1/liquid/send][%d] PeerSwap_LiquidSendToAddress default  %+v", o._statusCode, o.Payload)
}

func (o *PeerSwapLiquidSendToAddressDefault) String() string {
	return fmt.Sprintf("[POST /v1/liquid/send][%d] PeerSwap_LiquidSendToAddress default  %+v", o._statusCode, o.Payload)
}

func (o *PeerSwapLiquidSendToAddressDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *PeerSwapLiquidSendToAddressDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
