// Code generated by go-swagger; DO NOT EDIT.

package peer_swap

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"peerswap-web/models"
)

// PeerSwapAddSusPeerReader is a Reader for the PeerSwapAddSusPeer structure.
type PeerSwapAddSusPeerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PeerSwapAddSusPeerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPeerSwapAddSusPeerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPeerSwapAddSusPeerDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPeerSwapAddSusPeerOK creates a PeerSwapAddSusPeerOK with default headers values
func NewPeerSwapAddSusPeerOK() *PeerSwapAddSusPeerOK {
	return &PeerSwapAddSusPeerOK{}
}

/*
PeerSwapAddSusPeerOK describes a response with status code 200, with default header values.

A successful response.
*/
type PeerSwapAddSusPeerOK struct {
	Payload *models.PeerswapPolicy
}

// IsSuccess returns true when this peer swap add sus peer o k response has a 2xx status code
func (o *PeerSwapAddSusPeerOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this peer swap add sus peer o k response has a 3xx status code
func (o *PeerSwapAddSusPeerOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this peer swap add sus peer o k response has a 4xx status code
func (o *PeerSwapAddSusPeerOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this peer swap add sus peer o k response has a 5xx status code
func (o *PeerSwapAddSusPeerOK) IsServerError() bool {
	return false
}

// IsCode returns true when this peer swap add sus peer o k response a status code equal to that given
func (o *PeerSwapAddSusPeerOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the peer swap add sus peer o k response
func (o *PeerSwapAddSusPeerOK) Code() int {
	return 200
}

func (o *PeerSwapAddSusPeerOK) Error() string {
	return fmt.Sprintf("[POST /v1/policy/peer/addsus][%d] peerSwapAddSusPeerOK  %+v", 200, o.Payload)
}

func (o *PeerSwapAddSusPeerOK) String() string {
	return fmt.Sprintf("[POST /v1/policy/peer/addsus][%d] peerSwapAddSusPeerOK  %+v", 200, o.Payload)
}

func (o *PeerSwapAddSusPeerOK) GetPayload() *models.PeerswapPolicy {
	return o.Payload
}

func (o *PeerSwapAddSusPeerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PeerswapPolicy)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPeerSwapAddSusPeerDefault creates a PeerSwapAddSusPeerDefault with default headers values
func NewPeerSwapAddSusPeerDefault(code int) *PeerSwapAddSusPeerDefault {
	return &PeerSwapAddSusPeerDefault{
		_statusCode: code,
	}
}

/*
PeerSwapAddSusPeerDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type PeerSwapAddSusPeerDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this peer swap add sus peer default response has a 2xx status code
func (o *PeerSwapAddSusPeerDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this peer swap add sus peer default response has a 3xx status code
func (o *PeerSwapAddSusPeerDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this peer swap add sus peer default response has a 4xx status code
func (o *PeerSwapAddSusPeerDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this peer swap add sus peer default response has a 5xx status code
func (o *PeerSwapAddSusPeerDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this peer swap add sus peer default response a status code equal to that given
func (o *PeerSwapAddSusPeerDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the peer swap add sus peer default response
func (o *PeerSwapAddSusPeerDefault) Code() int {
	return o._statusCode
}

func (o *PeerSwapAddSusPeerDefault) Error() string {
	return fmt.Sprintf("[POST /v1/policy/peer/addsus][%d] PeerSwap_AddSusPeer default  %+v", o._statusCode, o.Payload)
}

func (o *PeerSwapAddSusPeerDefault) String() string {
	return fmt.Sprintf("[POST /v1/policy/peer/addsus][%d] PeerSwap_AddSusPeer default  %+v", o._statusCode, o.Payload)
}

func (o *PeerSwapAddSusPeerDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *PeerSwapAddSusPeerDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
