// Code generated by go-swagger; DO NOT EDIT.

package peer_swap

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"peerswap-web/models"
)

// NewPeerSwapRemoveSusPeerParams creates a new PeerSwapRemoveSusPeerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPeerSwapRemoveSusPeerParams() *PeerSwapRemoveSusPeerParams {
	return &PeerSwapRemoveSusPeerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPeerSwapRemoveSusPeerParamsWithTimeout creates a new PeerSwapRemoveSusPeerParams object
// with the ability to set a timeout on a request.
func NewPeerSwapRemoveSusPeerParamsWithTimeout(timeout time.Duration) *PeerSwapRemoveSusPeerParams {
	return &PeerSwapRemoveSusPeerParams{
		timeout: timeout,
	}
}

// NewPeerSwapRemoveSusPeerParamsWithContext creates a new PeerSwapRemoveSusPeerParams object
// with the ability to set a context for a request.
func NewPeerSwapRemoveSusPeerParamsWithContext(ctx context.Context) *PeerSwapRemoveSusPeerParams {
	return &PeerSwapRemoveSusPeerParams{
		Context: ctx,
	}
}

// NewPeerSwapRemoveSusPeerParamsWithHTTPClient creates a new PeerSwapRemoveSusPeerParams object
// with the ability to set a custom HTTPClient for a request.
func NewPeerSwapRemoveSusPeerParamsWithHTTPClient(client *http.Client) *PeerSwapRemoveSusPeerParams {
	return &PeerSwapRemoveSusPeerParams{
		HTTPClient: client,
	}
}

/*
PeerSwapRemoveSusPeerParams contains all the parameters to send to the API endpoint

	for the peer swap remove sus peer operation.

	Typically these are written to a http.Request.
*/
type PeerSwapRemoveSusPeerParams struct {

	// Body.
	Body *models.PeerswapRemovePeerRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the peer swap remove sus peer params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PeerSwapRemoveSusPeerParams) WithDefaults() *PeerSwapRemoveSusPeerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the peer swap remove sus peer params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PeerSwapRemoveSusPeerParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the peer swap remove sus peer params
func (o *PeerSwapRemoveSusPeerParams) WithTimeout(timeout time.Duration) *PeerSwapRemoveSusPeerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the peer swap remove sus peer params
func (o *PeerSwapRemoveSusPeerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the peer swap remove sus peer params
func (o *PeerSwapRemoveSusPeerParams) WithContext(ctx context.Context) *PeerSwapRemoveSusPeerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the peer swap remove sus peer params
func (o *PeerSwapRemoveSusPeerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the peer swap remove sus peer params
func (o *PeerSwapRemoveSusPeerParams) WithHTTPClient(client *http.Client) *PeerSwapRemoveSusPeerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the peer swap remove sus peer params
func (o *PeerSwapRemoveSusPeerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the peer swap remove sus peer params
func (o *PeerSwapRemoveSusPeerParams) WithBody(body *models.PeerswapRemovePeerRequest) *PeerSwapRemoveSusPeerParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the peer swap remove sus peer params
func (o *PeerSwapRemoveSusPeerParams) SetBody(body *models.PeerswapRemovePeerRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PeerSwapRemoveSusPeerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
