// Code generated by go-swagger; DO NOT EDIT.

package peer_swap

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"peerswap-web/models"
)

// NewPeerSwapSwapOutParams creates a new PeerSwapSwapOutParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPeerSwapSwapOutParams() *PeerSwapSwapOutParams {
	return &PeerSwapSwapOutParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPeerSwapSwapOutParamsWithTimeout creates a new PeerSwapSwapOutParams object
// with the ability to set a timeout on a request.
func NewPeerSwapSwapOutParamsWithTimeout(timeout time.Duration) *PeerSwapSwapOutParams {
	return &PeerSwapSwapOutParams{
		timeout: timeout,
	}
}

// NewPeerSwapSwapOutParamsWithContext creates a new PeerSwapSwapOutParams object
// with the ability to set a context for a request.
func NewPeerSwapSwapOutParamsWithContext(ctx context.Context) *PeerSwapSwapOutParams {
	return &PeerSwapSwapOutParams{
		Context: ctx,
	}
}

// NewPeerSwapSwapOutParamsWithHTTPClient creates a new PeerSwapSwapOutParams object
// with the ability to set a custom HTTPClient for a request.
func NewPeerSwapSwapOutParamsWithHTTPClient(client *http.Client) *PeerSwapSwapOutParams {
	return &PeerSwapSwapOutParams{
		HTTPClient: client,
	}
}

/*
PeerSwapSwapOutParams contains all the parameters to send to the API endpoint

	for the peer swap swap out operation.

	Typically these are written to a http.Request.
*/
type PeerSwapSwapOutParams struct {

	// Body.
	Body *models.PeerswapSwapOutRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the peer swap swap out params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PeerSwapSwapOutParams) WithDefaults() *PeerSwapSwapOutParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the peer swap swap out params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PeerSwapSwapOutParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the peer swap swap out params
func (o *PeerSwapSwapOutParams) WithTimeout(timeout time.Duration) *PeerSwapSwapOutParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the peer swap swap out params
func (o *PeerSwapSwapOutParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the peer swap swap out params
func (o *PeerSwapSwapOutParams) WithContext(ctx context.Context) *PeerSwapSwapOutParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the peer swap swap out params
func (o *PeerSwapSwapOutParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the peer swap swap out params
func (o *PeerSwapSwapOutParams) WithHTTPClient(client *http.Client) *PeerSwapSwapOutParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the peer swap swap out params
func (o *PeerSwapSwapOutParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the peer swap swap out params
func (o *PeerSwapSwapOutParams) WithBody(body *models.PeerswapSwapOutRequest) *PeerSwapSwapOutParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the peer swap swap out params
func (o *PeerSwapSwapOutParams) SetBody(body *models.PeerswapSwapOutRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PeerSwapSwapOutParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
