// Code generated by go-swagger; DO NOT EDIT.

package peer_swap

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPeerSwapLiquidGetAddressParams creates a new PeerSwapLiquidGetAddressParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPeerSwapLiquidGetAddressParams() *PeerSwapLiquidGetAddressParams {
	return &PeerSwapLiquidGetAddressParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPeerSwapLiquidGetAddressParamsWithTimeout creates a new PeerSwapLiquidGetAddressParams object
// with the ability to set a timeout on a request.
func NewPeerSwapLiquidGetAddressParamsWithTimeout(timeout time.Duration) *PeerSwapLiquidGetAddressParams {
	return &PeerSwapLiquidGetAddressParams{
		timeout: timeout,
	}
}

// NewPeerSwapLiquidGetAddressParamsWithContext creates a new PeerSwapLiquidGetAddressParams object
// with the ability to set a context for a request.
func NewPeerSwapLiquidGetAddressParamsWithContext(ctx context.Context) *PeerSwapLiquidGetAddressParams {
	return &PeerSwapLiquidGetAddressParams{
		Context: ctx,
	}
}

// NewPeerSwapLiquidGetAddressParamsWithHTTPClient creates a new PeerSwapLiquidGetAddressParams object
// with the ability to set a custom HTTPClient for a request.
func NewPeerSwapLiquidGetAddressParamsWithHTTPClient(client *http.Client) *PeerSwapLiquidGetAddressParams {
	return &PeerSwapLiquidGetAddressParams{
		HTTPClient: client,
	}
}

/*
PeerSwapLiquidGetAddressParams contains all the parameters to send to the API endpoint

	for the peer swap liquid get address operation.

	Typically these are written to a http.Request.
*/
type PeerSwapLiquidGetAddressParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the peer swap liquid get address params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PeerSwapLiquidGetAddressParams) WithDefaults() *PeerSwapLiquidGetAddressParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the peer swap liquid get address params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PeerSwapLiquidGetAddressParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the peer swap liquid get address params
func (o *PeerSwapLiquidGetAddressParams) WithTimeout(timeout time.Duration) *PeerSwapLiquidGetAddressParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the peer swap liquid get address params
func (o *PeerSwapLiquidGetAddressParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the peer swap liquid get address params
func (o *PeerSwapLiquidGetAddressParams) WithContext(ctx context.Context) *PeerSwapLiquidGetAddressParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the peer swap liquid get address params
func (o *PeerSwapLiquidGetAddressParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the peer swap liquid get address params
func (o *PeerSwapLiquidGetAddressParams) WithHTTPClient(client *http.Client) *PeerSwapLiquidGetAddressParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the peer swap liquid get address params
func (o *PeerSwapLiquidGetAddressParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PeerSwapLiquidGetAddressParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
