// Code generated by go-swagger; DO NOT EDIT.

package peer_swap

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"peerswap-web/models"
)

// PeerSwapListSwapsReader is a Reader for the PeerSwapListSwaps structure.
type PeerSwapListSwapsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PeerSwapListSwapsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPeerSwapListSwapsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPeerSwapListSwapsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPeerSwapListSwapsOK creates a PeerSwapListSwapsOK with default headers values
func NewPeerSwapListSwapsOK() *PeerSwapListSwapsOK {
	return &PeerSwapListSwapsOK{}
}

/*
PeerSwapListSwapsOK describes a response with status code 200, with default header values.

A successful response.
*/
type PeerSwapListSwapsOK struct {
	Payload *models.PeerswapListSwapsResponse
}

// IsSuccess returns true when this peer swap list swaps o k response has a 2xx status code
func (o *PeerSwapListSwapsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this peer swap list swaps o k response has a 3xx status code
func (o *PeerSwapListSwapsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this peer swap list swaps o k response has a 4xx status code
func (o *PeerSwapListSwapsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this peer swap list swaps o k response has a 5xx status code
func (o *PeerSwapListSwapsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this peer swap list swaps o k response a status code equal to that given
func (o *PeerSwapListSwapsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the peer swap list swaps o k response
func (o *PeerSwapListSwapsOK) Code() int {
	return 200
}

func (o *PeerSwapListSwapsOK) Error() string {
	return fmt.Sprintf("[GET /v1/swaps][%d] peerSwapListSwapsOK  %+v", 200, o.Payload)
}

func (o *PeerSwapListSwapsOK) String() string {
	return fmt.Sprintf("[GET /v1/swaps][%d] peerSwapListSwapsOK  %+v", 200, o.Payload)
}

func (o *PeerSwapListSwapsOK) GetPayload() *models.PeerswapListSwapsResponse {
	return o.Payload
}

func (o *PeerSwapListSwapsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PeerswapListSwapsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPeerSwapListSwapsDefault creates a PeerSwapListSwapsDefault with default headers values
func NewPeerSwapListSwapsDefault(code int) *PeerSwapListSwapsDefault {
	return &PeerSwapListSwapsDefault{
		_statusCode: code,
	}
}

/*
PeerSwapListSwapsDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type PeerSwapListSwapsDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this peer swap list swaps default response has a 2xx status code
func (o *PeerSwapListSwapsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this peer swap list swaps default response has a 3xx status code
func (o *PeerSwapListSwapsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this peer swap list swaps default response has a 4xx status code
func (o *PeerSwapListSwapsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this peer swap list swaps default response has a 5xx status code
func (o *PeerSwapListSwapsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this peer swap list swaps default response a status code equal to that given
func (o *PeerSwapListSwapsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the peer swap list swaps default response
func (o *PeerSwapListSwapsDefault) Code() int {
	return o._statusCode
}

func (o *PeerSwapListSwapsDefault) Error() string {
	return fmt.Sprintf("[GET /v1/swaps][%d] PeerSwap_ListSwaps default  %+v", o._statusCode, o.Payload)
}

func (o *PeerSwapListSwapsDefault) String() string {
	return fmt.Sprintf("[GET /v1/swaps][%d] PeerSwap_ListSwaps default  %+v", o._statusCode, o.Payload)
}

func (o *PeerSwapListSwapsDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *PeerSwapListSwapsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
