// Code generated by go-swagger; DO NOT EDIT.

package peer_swap

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"peerswap-web/models"
)

// PeerSwapAddPeerReader is a Reader for the PeerSwapAddPeer structure.
type PeerSwapAddPeerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PeerSwapAddPeerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPeerSwapAddPeerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPeerSwapAddPeerDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPeerSwapAddPeerOK creates a PeerSwapAddPeerOK with default headers values
func NewPeerSwapAddPeerOK() *PeerSwapAddPeerOK {
	return &PeerSwapAddPeerOK{}
}

/*
PeerSwapAddPeerOK describes a response with status code 200, with default header values.

A successful response.
*/
type PeerSwapAddPeerOK struct {
	Payload *models.PeerswapPolicy
}

// IsSuccess returns true when this peer swap add peer o k response has a 2xx status code
func (o *PeerSwapAddPeerOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this peer swap add peer o k response has a 3xx status code
func (o *PeerSwapAddPeerOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this peer swap add peer o k response has a 4xx status code
func (o *PeerSwapAddPeerOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this peer swap add peer o k response has a 5xx status code
func (o *PeerSwapAddPeerOK) IsServerError() bool {
	return false
}

// IsCode returns true when this peer swap add peer o k response a status code equal to that given
func (o *PeerSwapAddPeerOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the peer swap add peer o k response
func (o *PeerSwapAddPeerOK) Code() int {
	return 200
}

func (o *PeerSwapAddPeerOK) Error() string {
	return fmt.Sprintf("[POST /v1/policy/peer/add][%d] peerSwapAddPeerOK  %+v", 200, o.Payload)
}

func (o *PeerSwapAddPeerOK) String() string {
	return fmt.Sprintf("[POST /v1/policy/peer/add][%d] peerSwapAddPeerOK  %+v", 200, o.Payload)
}

func (o *PeerSwapAddPeerOK) GetPayload() *models.PeerswapPolicy {
	return o.Payload
}

func (o *PeerSwapAddPeerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PeerswapPolicy)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPeerSwapAddPeerDefault creates a PeerSwapAddPeerDefault with default headers values
func NewPeerSwapAddPeerDefault(code int) *PeerSwapAddPeerDefault {
	return &PeerSwapAddPeerDefault{
		_statusCode: code,
	}
}

/*
PeerSwapAddPeerDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type PeerSwapAddPeerDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this peer swap add peer default response has a 2xx status code
func (o *PeerSwapAddPeerDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this peer swap add peer default response has a 3xx status code
func (o *PeerSwapAddPeerDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this peer swap add peer default response has a 4xx status code
func (o *PeerSwapAddPeerDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this peer swap add peer default response has a 5xx status code
func (o *PeerSwapAddPeerDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this peer swap add peer default response a status code equal to that given
func (o *PeerSwapAddPeerDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the peer swap add peer default response
func (o *PeerSwapAddPeerDefault) Code() int {
	return o._statusCode
}

func (o *PeerSwapAddPeerDefault) Error() string {
	return fmt.Sprintf("[POST /v1/policy/peer/add][%d] PeerSwap_AddPeer default  %+v", o._statusCode, o.Payload)
}

func (o *PeerSwapAddPeerDefault) String() string {
	return fmt.Sprintf("[POST /v1/policy/peer/add][%d] PeerSwap_AddPeer default  %+v", o._statusCode, o.Payload)
}

func (o *PeerSwapAddPeerDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *PeerSwapAddPeerDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
