// Code generated by go-swagger; DO NOT EDIT.

package peer_swap

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"peerswap-web/models"
)

// PeerSwapRemovePeerReader is a Reader for the PeerSwapRemovePeer structure.
type PeerSwapRemovePeerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PeerSwapRemovePeerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPeerSwapRemovePeerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPeerSwapRemovePeerDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPeerSwapRemovePeerOK creates a PeerSwapRemovePeerOK with default headers values
func NewPeerSwapRemovePeerOK() *PeerSwapRemovePeerOK {
	return &PeerSwapRemovePeerOK{}
}

/*
PeerSwapRemovePeerOK describes a response with status code 200, with default header values.

A successful response.
*/
type PeerSwapRemovePeerOK struct {
	Payload *models.PeerswapPolicy
}

// IsSuccess returns true when this peer swap remove peer o k response has a 2xx status code
func (o *PeerSwapRemovePeerOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this peer swap remove peer o k response has a 3xx status code
func (o *PeerSwapRemovePeerOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this peer swap remove peer o k response has a 4xx status code
func (o *PeerSwapRemovePeerOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this peer swap remove peer o k response has a 5xx status code
func (o *PeerSwapRemovePeerOK) IsServerError() bool {
	return false
}

// IsCode returns true when this peer swap remove peer o k response a status code equal to that given
func (o *PeerSwapRemovePeerOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the peer swap remove peer o k response
func (o *PeerSwapRemovePeerOK) Code() int {
	return 200
}

func (o *PeerSwapRemovePeerOK) Error() string {
	return fmt.Sprintf("[POST /v1/policy/peer/remove][%d] peerSwapRemovePeerOK  %+v", 200, o.Payload)
}

func (o *PeerSwapRemovePeerOK) String() string {
	return fmt.Sprintf("[POST /v1/policy/peer/remove][%d] peerSwapRemovePeerOK  %+v", 200, o.Payload)
}

func (o *PeerSwapRemovePeerOK) GetPayload() *models.PeerswapPolicy {
	return o.Payload
}

func (o *PeerSwapRemovePeerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PeerswapPolicy)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPeerSwapRemovePeerDefault creates a PeerSwapRemovePeerDefault with default headers values
func NewPeerSwapRemovePeerDefault(code int) *PeerSwapRemovePeerDefault {
	return &PeerSwapRemovePeerDefault{
		_statusCode: code,
	}
}

/*
PeerSwapRemovePeerDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type PeerSwapRemovePeerDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this peer swap remove peer default response has a 2xx status code
func (o *PeerSwapRemovePeerDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this peer swap remove peer default response has a 3xx status code
func (o *PeerSwapRemovePeerDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this peer swap remove peer default response has a 4xx status code
func (o *PeerSwapRemovePeerDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this peer swap remove peer default response has a 5xx status code
func (o *PeerSwapRemovePeerDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this peer swap remove peer default response a status code equal to that given
func (o *PeerSwapRemovePeerDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the peer swap remove peer default response
func (o *PeerSwapRemovePeerDefault) Code() int {
	return o._statusCode
}

func (o *PeerSwapRemovePeerDefault) Error() string {
	return fmt.Sprintf("[POST /v1/policy/peer/remove][%d] PeerSwap_RemovePeer default  %+v", o._statusCode, o.Payload)
}

func (o *PeerSwapRemovePeerDefault) String() string {
	return fmt.Sprintf("[POST /v1/policy/peer/remove][%d] PeerSwap_RemovePeer default  %+v", o._statusCode, o.Payload)
}

func (o *PeerSwapRemovePeerDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *PeerSwapRemovePeerDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
