// Code generated by go-swagger; DO NOT EDIT.

package peer_swap

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"peerswap-web/models"
)

// NewPeerSwapLiquidSendToAddressParams creates a new PeerSwapLiquidSendToAddressParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPeerSwapLiquidSendToAddressParams() *PeerSwapLiquidSendToAddressParams {
	return &PeerSwapLiquidSendToAddressParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPeerSwapLiquidSendToAddressParamsWithTimeout creates a new PeerSwapLiquidSendToAddressParams object
// with the ability to set a timeout on a request.
func NewPeerSwapLiquidSendToAddressParamsWithTimeout(timeout time.Duration) *PeerSwapLiquidSendToAddressParams {
	return &PeerSwapLiquidSendToAddressParams{
		timeout: timeout,
	}
}

// NewPeerSwapLiquidSendToAddressParamsWithContext creates a new PeerSwapLiquidSendToAddressParams object
// with the ability to set a context for a request.
func NewPeerSwapLiquidSendToAddressParamsWithContext(ctx context.Context) *PeerSwapLiquidSendToAddressParams {
	return &PeerSwapLiquidSendToAddressParams{
		Context: ctx,
	}
}

// NewPeerSwapLiquidSendToAddressParamsWithHTTPClient creates a new PeerSwapLiquidSendToAddressParams object
// with the ability to set a custom HTTPClient for a request.
func NewPeerSwapLiquidSendToAddressParamsWithHTTPClient(client *http.Client) *PeerSwapLiquidSendToAddressParams {
	return &PeerSwapLiquidSendToAddressParams{
		HTTPClient: client,
	}
}

/*
PeerSwapLiquidSendToAddressParams contains all the parameters to send to the API endpoint

	for the peer swap liquid send to address operation.

	Typically these are written to a http.Request.
*/
type PeerSwapLiquidSendToAddressParams struct {

	// Body.
	Body *models.PeerswapSendToAddressRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the peer swap liquid send to address params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PeerSwapLiquidSendToAddressParams) WithDefaults() *PeerSwapLiquidSendToAddressParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the peer swap liquid send to address params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PeerSwapLiquidSendToAddressParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the peer swap liquid send to address params
func (o *PeerSwapLiquidSendToAddressParams) WithTimeout(timeout time.Duration) *PeerSwapLiquidSendToAddressParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the peer swap liquid send to address params
func (o *PeerSwapLiquidSendToAddressParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the peer swap liquid send to address params
func (o *PeerSwapLiquidSendToAddressParams) WithContext(ctx context.Context) *PeerSwapLiquidSendToAddressParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the peer swap liquid send to address params
func (o *PeerSwapLiquidSendToAddressParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the peer swap liquid send to address params
func (o *PeerSwapLiquidSendToAddressParams) WithHTTPClient(client *http.Client) *PeerSwapLiquidSendToAddressParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the peer swap liquid send to address params
func (o *PeerSwapLiquidSendToAddressParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the peer swap liquid send to address params
func (o *PeerSwapLiquidSendToAddressParams) WithBody(body *models.PeerswapSendToAddressRequest) *PeerSwapLiquidSendToAddressParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the peer swap liquid send to address params
func (o *PeerSwapLiquidSendToAddressParams) SetBody(body *models.PeerswapSendToAddressRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PeerSwapLiquidSendToAddressParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
