// Code generated by go-swagger; DO NOT EDIT.

package peer_swap

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPeerSwapReloadPolicyFileParams creates a new PeerSwapReloadPolicyFileParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPeerSwapReloadPolicyFileParams() *PeerSwapReloadPolicyFileParams {
	return &PeerSwapReloadPolicyFileParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPeerSwapReloadPolicyFileParamsWithTimeout creates a new PeerSwapReloadPolicyFileParams object
// with the ability to set a timeout on a request.
func NewPeerSwapReloadPolicyFileParamsWithTimeout(timeout time.Duration) *PeerSwapReloadPolicyFileParams {
	return &PeerSwapReloadPolicyFileParams{
		timeout: timeout,
	}
}

// NewPeerSwapReloadPolicyFileParamsWithContext creates a new PeerSwapReloadPolicyFileParams object
// with the ability to set a context for a request.
func NewPeerSwapReloadPolicyFileParamsWithContext(ctx context.Context) *PeerSwapReloadPolicyFileParams {
	return &PeerSwapReloadPolicyFileParams{
		Context: ctx,
	}
}

// NewPeerSwapReloadPolicyFileParamsWithHTTPClient creates a new PeerSwapReloadPolicyFileParams object
// with the ability to set a custom HTTPClient for a request.
func NewPeerSwapReloadPolicyFileParamsWithHTTPClient(client *http.Client) *PeerSwapReloadPolicyFileParams {
	return &PeerSwapReloadPolicyFileParams{
		HTTPClient: client,
	}
}

/*
PeerSwapReloadPolicyFileParams contains all the parameters to send to the API endpoint

	for the peer swap reload policy file operation.

	Typically these are written to a http.Request.
*/
type PeerSwapReloadPolicyFileParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the peer swap reload policy file params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PeerSwapReloadPolicyFileParams) WithDefaults() *PeerSwapReloadPolicyFileParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the peer swap reload policy file params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PeerSwapReloadPolicyFileParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the peer swap reload policy file params
func (o *PeerSwapReloadPolicyFileParams) WithTimeout(timeout time.Duration) *PeerSwapReloadPolicyFileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the peer swap reload policy file params
func (o *PeerSwapReloadPolicyFileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the peer swap reload policy file params
func (o *PeerSwapReloadPolicyFileParams) WithContext(ctx context.Context) *PeerSwapReloadPolicyFileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the peer swap reload policy file params
func (o *PeerSwapReloadPolicyFileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the peer swap reload policy file params
func (o *PeerSwapReloadPolicyFileParams) WithHTTPClient(client *http.Client) *PeerSwapReloadPolicyFileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the peer swap reload policy file params
func (o *PeerSwapReloadPolicyFileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PeerSwapReloadPolicyFileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
