// Code generated by go-swagger; DO NOT EDIT.

package peer_swap

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"peerswap-web/models"
)

// PeerSwapReloadPolicyFileReader is a Reader for the PeerSwapReloadPolicyFile structure.
type PeerSwapReloadPolicyFileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PeerSwapReloadPolicyFileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPeerSwapReloadPolicyFileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPeerSwapReloadPolicyFileDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPeerSwapReloadPolicyFileOK creates a PeerSwapReloadPolicyFileOK with default headers values
func NewPeerSwapReloadPolicyFileOK() *PeerSwapReloadPolicyFileOK {
	return &PeerSwapReloadPolicyFileOK{}
}

/*
PeerSwapReloadPolicyFileOK describes a response with status code 200, with default header values.

A successful response.
*/
type PeerSwapReloadPolicyFileOK struct {
	Payload *models.PeerswapPolicy
}

// IsSuccess returns true when this peer swap reload policy file o k response has a 2xx status code
func (o *PeerSwapReloadPolicyFileOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this peer swap reload policy file o k response has a 3xx status code
func (o *PeerSwapReloadPolicyFileOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this peer swap reload policy file o k response has a 4xx status code
func (o *PeerSwapReloadPolicyFileOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this peer swap reload policy file o k response has a 5xx status code
func (o *PeerSwapReloadPolicyFileOK) IsServerError() bool {
	return false
}

// IsCode returns true when this peer swap reload policy file o k response a status code equal to that given
func (o *PeerSwapReloadPolicyFileOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the peer swap reload policy file o k response
func (o *PeerSwapReloadPolicyFileOK) Code() int {
	return 200
}

func (o *PeerSwapReloadPolicyFileOK) Error() string {
	return fmt.Sprintf("[GET /v1/policy/reload][%d] peerSwapReloadPolicyFileOK  %+v", 200, o.Payload)
}

func (o *PeerSwapReloadPolicyFileOK) String() string {
	return fmt.Sprintf("[GET /v1/policy/reload][%d] peerSwapReloadPolicyFileOK  %+v", 200, o.Payload)
}

func (o *PeerSwapReloadPolicyFileOK) GetPayload() *models.PeerswapPolicy {
	return o.Payload
}

func (o *PeerSwapReloadPolicyFileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PeerswapPolicy)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPeerSwapReloadPolicyFileDefault creates a PeerSwapReloadPolicyFileDefault with default headers values
func NewPeerSwapReloadPolicyFileDefault(code int) *PeerSwapReloadPolicyFileDefault {
	return &PeerSwapReloadPolicyFileDefault{
		_statusCode: code,
	}
}

/*
PeerSwapReloadPolicyFileDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type PeerSwapReloadPolicyFileDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this peer swap reload policy file default response has a 2xx status code
func (o *PeerSwapReloadPolicyFileDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this peer swap reload policy file default response has a 3xx status code
func (o *PeerSwapReloadPolicyFileDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this peer swap reload policy file default response has a 4xx status code
func (o *PeerSwapReloadPolicyFileDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this peer swap reload policy file default response has a 5xx status code
func (o *PeerSwapReloadPolicyFileDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this peer swap reload policy file default response a status code equal to that given
func (o *PeerSwapReloadPolicyFileDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the peer swap reload policy file default response
func (o *PeerSwapReloadPolicyFileDefault) Code() int {
	return o._statusCode
}

func (o *PeerSwapReloadPolicyFileDefault) Error() string {
	return fmt.Sprintf("[GET /v1/policy/reload][%d] PeerSwap_ReloadPolicyFile default  %+v", o._statusCode, o.Payload)
}

func (o *PeerSwapReloadPolicyFileDefault) String() string {
	return fmt.Sprintf("[GET /v1/policy/reload][%d] PeerSwap_ReloadPolicyFile default  %+v", o._statusCode, o.Payload)
}

func (o *PeerSwapReloadPolicyFileDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *PeerSwapReloadPolicyFileDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
