// Code generated by go-swagger; DO NOT EDIT.

package peer_swap

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"peerswap-web/models"
)

// PeerSwapListPeersReader is a Reader for the PeerSwapListPeers structure.
type PeerSwapListPeersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PeerSwapListPeersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPeerSwapListPeersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPeerSwapListPeersDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPeerSwapListPeersOK creates a PeerSwapListPeersOK with default headers values
func NewPeerSwapListPeersOK() *PeerSwapListPeersOK {
	return &PeerSwapListPeersOK{}
}

/*
PeerSwapListPeersOK describes a response with status code 200, with default header values.

A successful response.
*/
type PeerSwapListPeersOK struct {
	Payload *models.PeerswapListPeersResponse
}

// IsSuccess returns true when this peer swap list peers o k response has a 2xx status code
func (o *PeerSwapListPeersOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this peer swap list peers o k response has a 3xx status code
func (o *PeerSwapListPeersOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this peer swap list peers o k response has a 4xx status code
func (o *PeerSwapListPeersOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this peer swap list peers o k response has a 5xx status code
func (o *PeerSwapListPeersOK) IsServerError() bool {
	return false
}

// IsCode returns true when this peer swap list peers o k response a status code equal to that given
func (o *PeerSwapListPeersOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the peer swap list peers o k response
func (o *PeerSwapListPeersOK) Code() int {
	return 200
}

func (o *PeerSwapListPeersOK) Error() string {
	return fmt.Sprintf("[GET /v1/peers][%d] peerSwapListPeersOK  %+v", 200, o.Payload)
}

func (o *PeerSwapListPeersOK) String() string {
	return fmt.Sprintf("[GET /v1/peers][%d] peerSwapListPeersOK  %+v", 200, o.Payload)
}

func (o *PeerSwapListPeersOK) GetPayload() *models.PeerswapListPeersResponse {
	return o.Payload
}

func (o *PeerSwapListPeersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PeerswapListPeersResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPeerSwapListPeersDefault creates a PeerSwapListPeersDefault with default headers values
func NewPeerSwapListPeersDefault(code int) *PeerSwapListPeersDefault {
	return &PeerSwapListPeersDefault{
		_statusCode: code,
	}
}

/*
PeerSwapListPeersDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type PeerSwapListPeersDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this peer swap list peers default response has a 2xx status code
func (o *PeerSwapListPeersDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this peer swap list peers default response has a 3xx status code
func (o *PeerSwapListPeersDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this peer swap list peers default response has a 4xx status code
func (o *PeerSwapListPeersDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this peer swap list peers default response has a 5xx status code
func (o *PeerSwapListPeersDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this peer swap list peers default response a status code equal to that given
func (o *PeerSwapListPeersDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the peer swap list peers default response
func (o *PeerSwapListPeersDefault) Code() int {
	return o._statusCode
}

func (o *PeerSwapListPeersDefault) Error() string {
	return fmt.Sprintf("[GET /v1/peers][%d] PeerSwap_ListPeers default  %+v", o._statusCode, o.Payload)
}

func (o *PeerSwapListPeersDefault) String() string {
	return fmt.Sprintf("[GET /v1/peers][%d] PeerSwap_ListPeers default  %+v", o._statusCode, o.Payload)
}

func (o *PeerSwapListPeersDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *PeerSwapListPeersDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
