// Code generated by go-swagger; DO NOT EDIT.

package peer_swap

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"peerswap-web/models"
)

// NewPeerSwapSwapInParams creates a new PeerSwapSwapInParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPeerSwapSwapInParams() *PeerSwapSwapInParams {
	return &PeerSwapSwapInParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPeerSwapSwapInParamsWithTimeout creates a new PeerSwapSwapInParams object
// with the ability to set a timeout on a request.
func NewPeerSwapSwapInParamsWithTimeout(timeout time.Duration) *PeerSwapSwapInParams {
	return &PeerSwapSwapInParams{
		timeout: timeout,
	}
}

// NewPeerSwapSwapInParamsWithContext creates a new PeerSwapSwapInParams object
// with the ability to set a context for a request.
func NewPeerSwapSwapInParamsWithContext(ctx context.Context) *PeerSwapSwapInParams {
	return &PeerSwapSwapInParams{
		Context: ctx,
	}
}

// NewPeerSwapSwapInParamsWithHTTPClient creates a new PeerSwapSwapInParams object
// with the ability to set a custom HTTPClient for a request.
func NewPeerSwapSwapInParamsWithHTTPClient(client *http.Client) *PeerSwapSwapInParams {
	return &PeerSwapSwapInParams{
		HTTPClient: client,
	}
}

/*
PeerSwapSwapInParams contains all the parameters to send to the API endpoint

	for the peer swap swap in operation.

	Typically these are written to a http.Request.
*/
type PeerSwapSwapInParams struct {

	// Body.
	Body *models.PeerswapSwapInRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the peer swap swap in params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PeerSwapSwapInParams) WithDefaults() *PeerSwapSwapInParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the peer swap swap in params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PeerSwapSwapInParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the peer swap swap in params
func (o *PeerSwapSwapInParams) WithTimeout(timeout time.Duration) *PeerSwapSwapInParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the peer swap swap in params
func (o *PeerSwapSwapInParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the peer swap swap in params
func (o *PeerSwapSwapInParams) WithContext(ctx context.Context) *PeerSwapSwapInParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the peer swap swap in params
func (o *PeerSwapSwapInParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the peer swap swap in params
func (o *PeerSwapSwapInParams) WithHTTPClient(client *http.Client) *PeerSwapSwapInParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the peer swap swap in params
func (o *PeerSwapSwapInParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the peer swap swap in params
func (o *PeerSwapSwapInParams) WithBody(body *models.PeerswapSwapInRequest) *PeerSwapSwapInParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the peer swap swap in params
func (o *PeerSwapSwapInParams) SetBody(body *models.PeerswapSwapInRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PeerSwapSwapInParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
