// Code generated by go-swagger; DO NOT EDIT.

package peer_swap

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPeerSwapListRequestedSwapsParams creates a new PeerSwapListRequestedSwapsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPeerSwapListRequestedSwapsParams() *PeerSwapListRequestedSwapsParams {
	return &PeerSwapListRequestedSwapsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPeerSwapListRequestedSwapsParamsWithTimeout creates a new PeerSwapListRequestedSwapsParams object
// with the ability to set a timeout on a request.
func NewPeerSwapListRequestedSwapsParamsWithTimeout(timeout time.Duration) *PeerSwapListRequestedSwapsParams {
	return &PeerSwapListRequestedSwapsParams{
		timeout: timeout,
	}
}

// NewPeerSwapListRequestedSwapsParamsWithContext creates a new PeerSwapListRequestedSwapsParams object
// with the ability to set a context for a request.
func NewPeerSwapListRequestedSwapsParamsWithContext(ctx context.Context) *PeerSwapListRequestedSwapsParams {
	return &PeerSwapListRequestedSwapsParams{
		Context: ctx,
	}
}

// NewPeerSwapListRequestedSwapsParamsWithHTTPClient creates a new PeerSwapListRequestedSwapsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPeerSwapListRequestedSwapsParamsWithHTTPClient(client *http.Client) *PeerSwapListRequestedSwapsParams {
	return &PeerSwapListRequestedSwapsParams{
		HTTPClient: client,
	}
}

/*
PeerSwapListRequestedSwapsParams contains all the parameters to send to the API endpoint

	for the peer swap list requested swaps operation.

	Typically these are written to a http.Request.
*/
type PeerSwapListRequestedSwapsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the peer swap list requested swaps params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PeerSwapListRequestedSwapsParams) WithDefaults() *PeerSwapListRequestedSwapsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the peer swap list requested swaps params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PeerSwapListRequestedSwapsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the peer swap list requested swaps params
func (o *PeerSwapListRequestedSwapsParams) WithTimeout(timeout time.Duration) *PeerSwapListRequestedSwapsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the peer swap list requested swaps params
func (o *PeerSwapListRequestedSwapsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the peer swap list requested swaps params
func (o *PeerSwapListRequestedSwapsParams) WithContext(ctx context.Context) *PeerSwapListRequestedSwapsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the peer swap list requested swaps params
func (o *PeerSwapListRequestedSwapsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the peer swap list requested swaps params
func (o *PeerSwapListRequestedSwapsParams) WithHTTPClient(client *http.Client) *PeerSwapListRequestedSwapsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the peer swap list requested swaps params
func (o *PeerSwapListRequestedSwapsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PeerSwapListRequestedSwapsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
