// Code generated by go-swagger; DO NOT EDIT.

package peer_swap

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"peerswap-web/models"
)

// PeerSwapRemoveSusPeerReader is a Reader for the PeerSwapRemoveSusPeer structure.
type PeerSwapRemoveSusPeerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PeerSwapRemoveSusPeerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPeerSwapRemoveSusPeerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPeerSwapRemoveSusPeerDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPeerSwapRemoveSusPeerOK creates a PeerSwapRemoveSusPeerOK with default headers values
func NewPeerSwapRemoveSusPeerOK() *PeerSwapRemoveSusPeerOK {
	return &PeerSwapRemoveSusPeerOK{}
}

/*
PeerSwapRemoveSusPeerOK describes a response with status code 200, with default header values.

A successful response.
*/
type PeerSwapRemoveSusPeerOK struct {
	Payload *models.PeerswapPolicy
}

// IsSuccess returns true when this peer swap remove sus peer o k response has a 2xx status code
func (o *PeerSwapRemoveSusPeerOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this peer swap remove sus peer o k response has a 3xx status code
func (o *PeerSwapRemoveSusPeerOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this peer swap remove sus peer o k response has a 4xx status code
func (o *PeerSwapRemoveSusPeerOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this peer swap remove sus peer o k response has a 5xx status code
func (o *PeerSwapRemoveSusPeerOK) IsServerError() bool {
	return false
}

// IsCode returns true when this peer swap remove sus peer o k response a status code equal to that given
func (o *PeerSwapRemoveSusPeerOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the peer swap remove sus peer o k response
func (o *PeerSwapRemoveSusPeerOK) Code() int {
	return 200
}

func (o *PeerSwapRemoveSusPeerOK) Error() string {
	return fmt.Sprintf("[POST /v1/policy/peer/removesus][%d] peerSwapRemoveSusPeerOK  %+v", 200, o.Payload)
}

func (o *PeerSwapRemoveSusPeerOK) String() string {
	return fmt.Sprintf("[POST /v1/policy/peer/removesus][%d] peerSwapRemoveSusPeerOK  %+v", 200, o.Payload)
}

func (o *PeerSwapRemoveSusPeerOK) GetPayload() *models.PeerswapPolicy {
	return o.Payload
}

func (o *PeerSwapRemoveSusPeerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PeerswapPolicy)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPeerSwapRemoveSusPeerDefault creates a PeerSwapRemoveSusPeerDefault with default headers values
func NewPeerSwapRemoveSusPeerDefault(code int) *PeerSwapRemoveSusPeerDefault {
	return &PeerSwapRemoveSusPeerDefault{
		_statusCode: code,
	}
}

/*
PeerSwapRemoveSusPeerDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type PeerSwapRemoveSusPeerDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this peer swap remove sus peer default response has a 2xx status code
func (o *PeerSwapRemoveSusPeerDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this peer swap remove sus peer default response has a 3xx status code
func (o *PeerSwapRemoveSusPeerDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this peer swap remove sus peer default response has a 4xx status code
func (o *PeerSwapRemoveSusPeerDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this peer swap remove sus peer default response has a 5xx status code
func (o *PeerSwapRemoveSusPeerDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this peer swap remove sus peer default response a status code equal to that given
func (o *PeerSwapRemoveSusPeerDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the peer swap remove sus peer default response
func (o *PeerSwapRemoveSusPeerDefault) Code() int {
	return o._statusCode
}

func (o *PeerSwapRemoveSusPeerDefault) Error() string {
	return fmt.Sprintf("[POST /v1/policy/peer/removesus][%d] PeerSwap_RemoveSusPeer default  %+v", o._statusCode, o.Payload)
}

func (o *PeerSwapRemoveSusPeerDefault) String() string {
	return fmt.Sprintf("[POST /v1/policy/peer/removesus][%d] PeerSwap_RemoveSusPeer default  %+v", o._statusCode, o.Payload)
}

func (o *PeerSwapRemoveSusPeerDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *PeerSwapRemoveSusPeerDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
