// Code generated by go-swagger; DO NOT EDIT.

package peer_swap

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPeerSwapLiquidGetBalanceParams creates a new PeerSwapLiquidGetBalanceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPeerSwapLiquidGetBalanceParams() *PeerSwapLiquidGetBalanceParams {
	return &PeerSwapLiquidGetBalanceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPeerSwapLiquidGetBalanceParamsWithTimeout creates a new PeerSwapLiquidGetBalanceParams object
// with the ability to set a timeout on a request.
func NewPeerSwapLiquidGetBalanceParamsWithTimeout(timeout time.Duration) *PeerSwapLiquidGetBalanceParams {
	return &PeerSwapLiquidGetBalanceParams{
		timeout: timeout,
	}
}

// NewPeerSwapLiquidGetBalanceParamsWithContext creates a new PeerSwapLiquidGetBalanceParams object
// with the ability to set a context for a request.
func NewPeerSwapLiquidGetBalanceParamsWithContext(ctx context.Context) *PeerSwapLiquidGetBalanceParams {
	return &PeerSwapLiquidGetBalanceParams{
		Context: ctx,
	}
}

// NewPeerSwapLiquidGetBalanceParamsWithHTTPClient creates a new PeerSwapLiquidGetBalanceParams object
// with the ability to set a custom HTTPClient for a request.
func NewPeerSwapLiquidGetBalanceParamsWithHTTPClient(client *http.Client) *PeerSwapLiquidGetBalanceParams {
	return &PeerSwapLiquidGetBalanceParams{
		HTTPClient: client,
	}
}

/*
PeerSwapLiquidGetBalanceParams contains all the parameters to send to the API endpoint

	for the peer swap liquid get balance operation.

	Typically these are written to a http.Request.
*/
type PeerSwapLiquidGetBalanceParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the peer swap liquid get balance params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PeerSwapLiquidGetBalanceParams) WithDefaults() *PeerSwapLiquidGetBalanceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the peer swap liquid get balance params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PeerSwapLiquidGetBalanceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the peer swap liquid get balance params
func (o *PeerSwapLiquidGetBalanceParams) WithTimeout(timeout time.Duration) *PeerSwapLiquidGetBalanceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the peer swap liquid get balance params
func (o *PeerSwapLiquidGetBalanceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the peer swap liquid get balance params
func (o *PeerSwapLiquidGetBalanceParams) WithContext(ctx context.Context) *PeerSwapLiquidGetBalanceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the peer swap liquid get balance params
func (o *PeerSwapLiquidGetBalanceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the peer swap liquid get balance params
func (o *PeerSwapLiquidGetBalanceParams) WithHTTPClient(client *http.Client) *PeerSwapLiquidGetBalanceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the peer swap liquid get balance params
func (o *PeerSwapLiquidGetBalanceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PeerSwapLiquidGetBalanceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
