// Code generated by go-swagger; DO NOT EDIT.

package peer_swap

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"peerswap-web/models"
)

// PeerSwapGetSwapReader is a Reader for the PeerSwapGetSwap structure.
type PeerSwapGetSwapReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PeerSwapGetSwapReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPeerSwapGetSwapOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPeerSwapGetSwapDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPeerSwapGetSwapOK creates a PeerSwapGetSwapOK with default headers values
func NewPeerSwapGetSwapOK() *PeerSwapGetSwapOK {
	return &PeerSwapGetSwapOK{}
}

/*
PeerSwapGetSwapOK describes a response with status code 200, with default header values.

A successful response.
*/
type PeerSwapGetSwapOK struct {
	Payload *models.PeerswapSwapResponse
}

// IsSuccess returns true when this peer swap get swap o k response has a 2xx status code
func (o *PeerSwapGetSwapOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this peer swap get swap o k response has a 3xx status code
func (o *PeerSwapGetSwapOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this peer swap get swap o k response has a 4xx status code
func (o *PeerSwapGetSwapOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this peer swap get swap o k response has a 5xx status code
func (o *PeerSwapGetSwapOK) IsServerError() bool {
	return false
}

// IsCode returns true when this peer swap get swap o k response a status code equal to that given
func (o *PeerSwapGetSwapOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the peer swap get swap o k response
func (o *PeerSwapGetSwapOK) Code() int {
	return 200
}

func (o *PeerSwapGetSwapOK) Error() string {
	return fmt.Sprintf("[GET /v1/swaps/{swapId}][%d] peerSwapGetSwapOK  %+v", 200, o.Payload)
}

func (o *PeerSwapGetSwapOK) String() string {
	return fmt.Sprintf("[GET /v1/swaps/{swapId}][%d] peerSwapGetSwapOK  %+v", 200, o.Payload)
}

func (o *PeerSwapGetSwapOK) GetPayload() *models.PeerswapSwapResponse {
	return o.Payload
}

func (o *PeerSwapGetSwapOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PeerswapSwapResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPeerSwapGetSwapDefault creates a PeerSwapGetSwapDefault with default headers values
func NewPeerSwapGetSwapDefault(code int) *PeerSwapGetSwapDefault {
	return &PeerSwapGetSwapDefault{
		_statusCode: code,
	}
}

/*
PeerSwapGetSwapDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type PeerSwapGetSwapDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this peer swap get swap default response has a 2xx status code
func (o *PeerSwapGetSwapDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this peer swap get swap default response has a 3xx status code
func (o *PeerSwapGetSwapDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this peer swap get swap default response has a 4xx status code
func (o *PeerSwapGetSwapDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this peer swap get swap default response has a 5xx status code
func (o *PeerSwapGetSwapDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this peer swap get swap default response a status code equal to that given
func (o *PeerSwapGetSwapDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the peer swap get swap default response
func (o *PeerSwapGetSwapDefault) Code() int {
	return o._statusCode
}

func (o *PeerSwapGetSwapDefault) Error() string {
	return fmt.Sprintf("[GET /v1/swaps/{swapId}][%d] PeerSwap_GetSwap default  %+v", o._statusCode, o.Payload)
}

func (o *PeerSwapGetSwapDefault) String() string {
	return fmt.Sprintf("[GET /v1/swaps/{swapId}][%d] PeerSwap_GetSwap default  %+v", o._statusCode, o.Payload)
}

func (o *PeerSwapGetSwapDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *PeerSwapGetSwapDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
