// Code generated by go-swagger; DO NOT EDIT.

package peer_swap

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPeerSwapListActiveSwapsParams creates a new PeerSwapListActiveSwapsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPeerSwapListActiveSwapsParams() *PeerSwapListActiveSwapsParams {
	return &PeerSwapListActiveSwapsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPeerSwapListActiveSwapsParamsWithTimeout creates a new PeerSwapListActiveSwapsParams object
// with the ability to set a timeout on a request.
func NewPeerSwapListActiveSwapsParamsWithTimeout(timeout time.Duration) *PeerSwapListActiveSwapsParams {
	return &PeerSwapListActiveSwapsParams{
		timeout: timeout,
	}
}

// NewPeerSwapListActiveSwapsParamsWithContext creates a new PeerSwapListActiveSwapsParams object
// with the ability to set a context for a request.
func NewPeerSwapListActiveSwapsParamsWithContext(ctx context.Context) *PeerSwapListActiveSwapsParams {
	return &PeerSwapListActiveSwapsParams{
		Context: ctx,
	}
}

// NewPeerSwapListActiveSwapsParamsWithHTTPClient creates a new PeerSwapListActiveSwapsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPeerSwapListActiveSwapsParamsWithHTTPClient(client *http.Client) *PeerSwapListActiveSwapsParams {
	return &PeerSwapListActiveSwapsParams{
		HTTPClient: client,
	}
}

/*
PeerSwapListActiveSwapsParams contains all the parameters to send to the API endpoint

	for the peer swap list active swaps operation.

	Typically these are written to a http.Request.
*/
type PeerSwapListActiveSwapsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the peer swap list active swaps params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PeerSwapListActiveSwapsParams) WithDefaults() *PeerSwapListActiveSwapsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the peer swap list active swaps params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PeerSwapListActiveSwapsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the peer swap list active swaps params
func (o *PeerSwapListActiveSwapsParams) WithTimeout(timeout time.Duration) *PeerSwapListActiveSwapsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the peer swap list active swaps params
func (o *PeerSwapListActiveSwapsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the peer swap list active swaps params
func (o *PeerSwapListActiveSwapsParams) WithContext(ctx context.Context) *PeerSwapListActiveSwapsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the peer swap list active swaps params
func (o *PeerSwapListActiveSwapsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the peer swap list active swaps params
func (o *PeerSwapListActiveSwapsParams) WithHTTPClient(client *http.Client) *PeerSwapListActiveSwapsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the peer swap list active swaps params
func (o *PeerSwapListActiveSwapsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PeerSwapListActiveSwapsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
