name: Build Docker Images
permissions:
  packages: write

on:
  push:
    tags:
      - 'v*'  # Trigger on tags starting with 'v'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: New builder
        run: |
          docker run --privileged --rm tonistiigi/binfmt --install all
          docker buildx create --use --name newbuilder
    
      - name: Build Docker image and push to registry
        run: |
          docker buildx build \
            --platform linux/arm64,linux/amd64 \
            --tag ghcr.io/impa10r/peerswap-web:${GITHUB_REF#refs/tags/} \
            --tag ghcr.io/impa10r/peerswap-web:latest \
            --output "type=registry" \
            .
