name: Manual Workflow Trigger

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Build Docker image and push to registry
        run: |
          docker buildx build \
            --platform linux/arm64,linux/amd64 \
            --tag ghcr.io/impa10r/peerswap-web:v1.2.4 \
            --tag ghcr.io/impa10r/peerswap-web:latest \
            --output "type=registry" \
            .