// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PeerswapSendToAddressResponse peerswap send to address response
//
// swagger:model peerswapSendToAddressResponse
type PeerswapSendToAddressResponse struct {

	// tx Id
	TxID string `json:"txId,omitempty"`
}

// Validate validates this peerswap send to address response
func (m *PeerswapSendToAddressResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this peerswap send to address response based on context it is used
func (m *PeerswapSendToAddressResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PeerswapSendToAddressResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PeerswapSendToAddressResponse) UnmarshalBinary(b []byte) error {
	var res PeerswapSendToAddressResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
