// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PeerswapPeerSwapPeerChannel peerswap peer swap peer channel
//
// swagger:model peerswapPeerSwapPeerChannel
type PeerswapPeerSwapPeerChannel struct {

	// active
	Active bool `json:"active,omitempty"`

	// channel Id
	ChannelID string `json:"channelId,omitempty"`

	// local balance
	LocalBalance string `json:"localBalance,omitempty"`

	// remote balance
	RemoteBalance string `json:"remoteBalance,omitempty"`
}

// Validate validates this peerswap peer swap peer channel
func (m *PeerswapPeerSwapPeerChannel) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this peerswap peer swap peer channel based on context it is used
func (m *PeerswapPeerSwapPeerChannel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PeerswapPeerSwapPeerChannel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PeerswapPeerSwapPeerChannel) UnmarshalBinary(b []byte) error {
	var res PeerswapPeerSwapPeerChannel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
