// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PeerswapSwapStats peerswap swap stats
//
// swagger:model peerswapSwapStats
type PeerswapSwapStats struct {

	// sats in
	SatsIn string `json:"satsIn,omitempty"`

	// sats out
	SatsOut string `json:"satsOut,omitempty"`

	// swaps in
	SwapsIn string `json:"swapsIn,omitempty"`

	// swaps out
	SwapsOut string `json:"swapsOut,omitempty"`
}

// Validate validates this peerswap swap stats
func (m *PeerswapSwapStats) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this peerswap swap stats based on context it is used
func (m *PeerswapSwapStats) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PeerswapSwapStats) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PeerswapSwapStats) UnmarshalBinary(b []byte) error {
	var res PeerswapSwapStats
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
