// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PeerswapSendToAddressRequest peerswap send to address request
//
// swagger:model peerswapSendToAddressRequest
type PeerswapSendToAddressRequest struct {

	// address
	Address string `json:"address,omitempty"`

	// sat amount
	SatAmount string `json:"satAmount,omitempty"`
}

// Validate validates this peerswap send to address request
func (m *PeerswapSendToAddressRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this peerswap send to address request based on context it is used
func (m *PeerswapSendToAddressRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PeerswapSendToAddressRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PeerswapSendToAddressRequest) UnmarshalBinary(b []byte) error {
	var res PeerswapSendToAddressRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
