// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PeerswapListRequestedSwapsResponse peerswap list requested swaps response
//
// swagger:model peerswapListRequestedSwapsResponse
type PeerswapListRequestedSwapsResponse struct {

	// requested swaps
	RequestedSwaps map[string]PeerswapRequestSwapList `json:"requestedSwaps,omitempty"`
}

// Validate validates this peerswap list requested swaps response
func (m *PeerswapListRequestedSwapsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRequestedSwaps(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PeerswapListRequestedSwapsResponse) validateRequestedSwaps(formats strfmt.Registry) error {
	if swag.IsZero(m.RequestedSwaps) { // not required
		return nil
	}

	for k := range m.RequestedSwaps {

		if err := validate.Required("requestedSwaps"+"."+k, "body", m.RequestedSwaps[k]); err != nil {
			return err
		}
		if val, ok := m.RequestedSwaps[k]; ok {
			if err := val.Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("requestedSwaps" + "." + k)
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("requestedSwaps" + "." + k)
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this peerswap list requested swaps response based on the context it is used
func (m *PeerswapListRequestedSwapsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateRequestedSwaps(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PeerswapListRequestedSwapsResponse) contextValidateRequestedSwaps(ctx context.Context, formats strfmt.Registry) error {

	for k := range m.RequestedSwaps {

		if val, ok := m.RequestedSwaps[k]; ok {
			if err := val.ContextValidate(ctx, formats); err != nil {
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PeerswapListRequestedSwapsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PeerswapListRequestedSwapsResponse) UnmarshalBinary(b []byte) error {
	var res PeerswapListRequestedSwapsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
