// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PeerswapListSwapsResponse peerswap list swaps response
//
// swagger:model peerswapListSwapsResponse
type PeerswapListSwapsResponse struct {

	// swaps
	Swaps []*PeerswapPrettyPrintSwap `json:"swaps"`
}

// Validate validates this peerswap list swaps response
func (m *PeerswapListSwapsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSwaps(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PeerswapListSwapsResponse) validateSwaps(formats strfmt.Registry) error {
	if swag.IsZero(m.Swaps) { // not required
		return nil
	}

	for i := 0; i < len(m.Swaps); i++ {
		if swag.IsZero(m.Swaps[i]) { // not required
			continue
		}

		if m.Swaps[i] != nil {
			if err := m.Swaps[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("swaps" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("swaps" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this peerswap list swaps response based on the context it is used
func (m *PeerswapListSwapsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSwaps(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PeerswapListSwapsResponse) contextValidateSwaps(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Swaps); i++ {

		if m.Swaps[i] != nil {

			if swag.IsZero(m.Swaps[i]) { // not required
				return nil
			}

			if err := m.Swaps[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("swaps" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("swaps" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PeerswapListSwapsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PeerswapListSwapsResponse) UnmarshalBinary(b []byte) error {
	var res PeerswapListSwapsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
