// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PeerswapRequestedSwap peerswap requested swap
//
// swagger:model peerswapRequestedSwap
type PeerswapRequestedSwap struct {

	// amount sat
	AmountSat string `json:"amountSat,omitempty"`

	// asset
	Asset string `json:"asset,omitempty"`

	// rejection reason
	RejectionReason string `json:"rejectionReason,omitempty"`

	// swap type
	SwapType *RequestedSwapSwapType `json:"swapType,omitempty"`
}

// Validate validates this peerswap requested swap
func (m *PeerswapRequestedSwap) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSwapType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PeerswapRequestedSwap) validateSwapType(formats strfmt.Registry) error {
	if swag.IsZero(m.SwapType) { // not required
		return nil
	}

	if m.SwapType != nil {
		if err := m.SwapType.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("swapType")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("swapType")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this peerswap requested swap based on the context it is used
func (m *PeerswapRequestedSwap) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSwapType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PeerswapRequestedSwap) contextValidateSwapType(ctx context.Context, formats strfmt.Registry) error {

	if m.SwapType != nil {

		if swag.IsZero(m.SwapType) { // not required
			return nil
		}

		if err := m.SwapType.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("swapType")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("swapType")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PeerswapRequestedSwap) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PeerswapRequestedSwap) UnmarshalBinary(b []byte) error {
	var res PeerswapRequestedSwap
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
