// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PeerswapSwapResponse peerswap swap response
//
// swagger:model peerswapSwapResponse
type PeerswapSwapResponse struct {

	// swap
	Swap *PeerswapPrettyPrintSwap `json:"swap,omitempty"`
}

// Validate validates this peerswap swap response
func (m *PeerswapSwapResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSwap(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PeerswapSwapResponse) validateSwap(formats strfmt.Registry) error {
	if swag.IsZero(m.Swap) { // not required
		return nil
	}

	if m.Swap != nil {
		if err := m.Swap.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("swap")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("swap")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this peerswap swap response based on the context it is used
func (m *PeerswapSwapResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSwap(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PeerswapSwapResponse) contextValidateSwap(ctx context.Context, formats strfmt.Registry) error {

	if m.Swap != nil {

		if swag.IsZero(m.Swap) { // not required
			return nil
		}

		if err := m.Swap.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("swap")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("swap")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PeerswapSwapResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PeerswapSwapResponse) UnmarshalBinary(b []byte) error {
	var res PeerswapSwapResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
