// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PeerswapAddPeerRequest peerswap add peer request
//
// swagger:model peerswapAddPeerRequest
type PeerswapAddPeerRequest struct {

	// peer pubkey
	PeerPubkey string `json:"peerPubkey,omitempty"`
}

// Validate validates this peerswap add peer request
func (m *PeerswapAddPeerRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this peerswap add peer request based on context it is used
func (m *PeerswapAddPeerRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PeerswapAddPeerRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PeerswapAddPeerRequest) UnmarshalBinary(b []byte) error {
	var res PeerswapAddPeerRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
