// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PeerswapGetBalanceResponse peerswap get balance response
//
// swagger:model peerswapGetBalanceResponse
type PeerswapGetBalanceResponse struct {

	// sat amount
	SatAmount string `json:"satAmount,omitempty"`
}

// Validate validates this peerswap get balance response
func (m *PeerswapGetBalanceResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this peerswap get balance response based on context it is used
func (m *PeerswapGetBalanceResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PeerswapGetBalanceResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PeerswapGetBalanceResponse) UnmarshalBinary(b []byte) error {
	var res PeerswapGetBalanceResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
