// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PeerswapPrettyPrintSwap peerswap pretty print swap
//
// swagger:model peerswapPrettyPrintSwap
type PeerswapPrettyPrintSwap struct {

	// amount
	Amount string `json:"amount,omitempty"`

	// asset
	Asset string `json:"asset,omitempty"`

	// cancel message
	CancelMessage string `json:"cancelMessage,omitempty"`

	// channel Id
	ChannelID string `json:"channelId,omitempty"`

	// claim tx Id
	ClaimTxID string `json:"claimTxId,omitempty"`

	// created at
	CreatedAt string `json:"createdAt,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// initiator node Id
	InitiatorNodeID string `json:"initiatorNodeId,omitempty"`

	// lnd chan Id
	LndChanID string `json:"lndChanId,omitempty"`

	// opening tx Id
	OpeningTxID string `json:"openingTxId,omitempty"`

	// peer node Id
	PeerNodeID string `json:"peerNodeId,omitempty"`

	// role
	Role string `json:"role,omitempty"`

	// state
	State string `json:"state,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this peerswap pretty print swap
func (m *PeerswapPrettyPrintSwap) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this peerswap pretty print swap based on context it is used
func (m *PeerswapPrettyPrintSwap) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PeerswapPrettyPrintSwap) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PeerswapPrettyPrintSwap) UnmarshalBinary(b []byte) error {
	var res PeerswapPrettyPrintSwap
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
