// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PeerswapSwapInRequest peerswap swap in request
//
// swagger:model peerswapSwapInRequest
type PeerswapSwapInRequest struct {

	// asset
	Asset string `json:"asset,omitempty"`

	// channel Id
	ChannelID string `json:"channelId,omitempty"`

	// force
	Force bool `json:"force,omitempty"`

	// swap amount
	SwapAmount string `json:"swapAmount,omitempty"`
}

// Validate validates this peerswap swap in request
func (m *PeerswapSwapInRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this peerswap swap in request based on context it is used
func (m *PeerswapSwapInRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PeerswapSwapInRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PeerswapSwapInRequest) UnmarshalBinary(b []byte) error {
	var res PeerswapSwapInRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
