// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PeerswapAllowSwapRequestsRequest peerswap allow swap requests request
//
// swagger:model peerswapAllowSwapRequestsRequest
type PeerswapAllowSwapRequestsRequest struct {

	// allow
	Allow bool `json:"allow,omitempty"`
}

// Validate validates this peerswap allow swap requests request
func (m *PeerswapAllowSwapRequestsRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this peerswap allow swap requests request based on context it is used
func (m *PeerswapAllowSwapRequestsRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PeerswapAllowSwapRequestsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PeerswapAllowSwapRequestsRequest) UnmarshalBinary(b []byte) error {
	var res PeerswapAllowSwapRequestsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
