// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PeerswapPeerSwapPeer peerswap peer swap peer
//
// swagger:model peerswapPeerSwapPeer
type PeerswapPeerSwapPeer struct {

	// as receiver
	AsReceiver *PeerswapSwapStats `json:"asReceiver,omitempty"`

	// as sender
	AsSender *PeerswapSwapStats `json:"asSender,omitempty"`

	// channels
	Channels []*PeerswapPeerSwapPeerChannel `json:"channels"`

	// node Id
	NodeID string `json:"nodeId,omitempty"`

	// paid fee
	PaidFee string `json:"paidFee,omitempty"`

	// supported assets
	SupportedAssets []string `json:"supportedAssets"`

	// swaps allowed
	SwapsAllowed bool `json:"swapsAllowed,omitempty"`
}

// Validate validates this peerswap peer swap peer
func (m *PeerswapPeerSwapPeer) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAsReceiver(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAsSender(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateChannels(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PeerswapPeerSwapPeer) validateAsReceiver(formats strfmt.Registry) error {
	if swag.IsZero(m.AsReceiver) { // not required
		return nil
	}

	if m.AsReceiver != nil {
		if err := m.AsReceiver.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("asReceiver")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("asReceiver")
			}
			return err
		}
	}

	return nil
}

func (m *PeerswapPeerSwapPeer) validateAsSender(formats strfmt.Registry) error {
	if swag.IsZero(m.AsSender) { // not required
		return nil
	}

	if m.AsSender != nil {
		if err := m.AsSender.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("asSender")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("asSender")
			}
			return err
		}
	}

	return nil
}

func (m *PeerswapPeerSwapPeer) validateChannels(formats strfmt.Registry) error {
	if swag.IsZero(m.Channels) { // not required
		return nil
	}

	for i := 0; i < len(m.Channels); i++ {
		if swag.IsZero(m.Channels[i]) { // not required
			continue
		}

		if m.Channels[i] != nil {
			if err := m.Channels[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("channels" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("channels" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this peerswap peer swap peer based on the context it is used
func (m *PeerswapPeerSwapPeer) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAsReceiver(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateAsSender(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateChannels(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PeerswapPeerSwapPeer) contextValidateAsReceiver(ctx context.Context, formats strfmt.Registry) error {

	if m.AsReceiver != nil {

		if swag.IsZero(m.AsReceiver) { // not required
			return nil
		}

		if err := m.AsReceiver.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("asReceiver")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("asReceiver")
			}
			return err
		}
	}

	return nil
}

func (m *PeerswapPeerSwapPeer) contextValidateAsSender(ctx context.Context, formats strfmt.Registry) error {

	if m.AsSender != nil {

		if swag.IsZero(m.AsSender) { // not required
			return nil
		}

		if err := m.AsSender.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("asSender")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("asSender")
			}
			return err
		}
	}

	return nil
}

func (m *PeerswapPeerSwapPeer) contextValidateChannels(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Channels); i++ {

		if m.Channels[i] != nil {

			if swag.IsZero(m.Channels[i]) { // not required
				return nil
			}

			if err := m.Channels[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("channels" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("channels" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PeerswapPeerSwapPeer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PeerswapPeerSwapPeer) UnmarshalBinary(b []byte) error {
	var res PeerswapPeerSwapPeer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
